database:
  host: "localhost"
  database: "particles"
  port: "3306"
  user: "root"
  password: "yourPassword"

messages: # Supports legacy and mini-message
  selected: "You selected %particle_name% as your particle effect!"
  stop: "You disabled your particle effect"
  missing_permission: "You disabled your particle effect"

particles:
  1:
    name: "Particle in slot 1!"
    item: "WATER_BUCKET"
    particle: "DRIP_WATER"
    permission: "particle.water"
  32:
    name: "Particle in slot 32!"
    item: "LAVA_BUCKET"
    particle: "DRIP_LAVA"
    permission: "particle.lava"
